# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f7940f2ad7f668fa8c6bbaf71186f6ffba1d9f17f72cdb896677684abf4ef071dffba048cc1a400b21e3e6bb4ccf0a95237cd09d983eeb4861a43594271263b0

test:
  secret_key_base: 40b735e3b44e0096e1613f9f7021a70316df540cb9bd1c0e9c5c4af30f578d9cdaf870a181f22b9b35a7f09830dadd1ab932f5f3d877f6626710d2a5ce9b926b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
